In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [3]:
C =tf.constant([7,10])
C.dtype

tf.int32

In [4]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B , dtype = tf.float16)
D, D.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [5]:
# Change from int32 to float32

E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [6]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16


<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

# Aggregating Tensors

Aggregating tensors : condensing them for multiple values down to a smaller amount of values

In [7]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [8]:
# Get the absoulte values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

## Let's go thorugh the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [9]:
import numpy as np
# Create a raondom tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100,size = 50))

In [10]:
tf.size(E), E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [11]:
# Find the minimum

tf.reduce_min(E)


<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [12]:
np.min(E)

5

In [13]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [14]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [15]:
# Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2339>

**Find the variance and standard variation**

In [19]:

import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=752>

In [ ]:
# Find the variance , we need access to tensorlfow probability
tfp.stats.variance(E)

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

In [ ]:
# Find the variance of our E tensor

tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

# Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
A = tf.random.uniform(shape = [50])
A

In [ ]:
# Find the positional maximum
tf.argmax(A)

In [ ]:
# Index on our largest value position
A[tf.argmax(A)]

In [ ]:
# Find the max value of A
tf.reduce_max(A)

In [ ]:
# Check the eqaulity
A[tf.argmax(A)] == tf.reduce_max(A)

In [ ]:
# Find the minimum

tf.argmin(A)

In [ ]:
# Index min
A[tf.argmin(A)]

In [ ]:
# Find the min value
tf.reduce_min(A)

In [ ]:
# Equality

A[tf.argmin(A)]== tf.reduce_min(A)

## Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor
tf.random.set_seed(42)
B = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,50))
B

In [ ]:
B.shape

In [ ]:
B_squeezed = tf.squeeze(B)
B_squeezed, B_squeezed.shape

## One-hot encoding tensors

In [ ]:
# Create a list of indices
list = [0,1,2,3] # could be red, green, blue, purple

# One hot encode our list of indices

tf.one_hot(list,depth = 4)

In [ ]:
# Specify custom values for one hot encoding

tf.one_hot(list,depth=4,on_value= "I love deep learning",off_value = "I hate machine learning")

In [ ]:
# Create a new tensor

C = tf.range(1,10)

In [ ]:
C

In [ ]:
# Square it

tf.square(C)

In [ ]:
# # Find the squareroot
tf.math.sqrt(tf.cast(C,dtype=tf.float32))

In [ ]:
# Find the log
tf.math.log(tf.cast(C,dtype=tf.float32))

## Tensors and Numpy

Tensorlfow interacts beautifully with Numpy arrays

In [ ]:
# Create a tensor directly from numpy arrays

T = tf.constant(np.array([3.,7.,10.]))
T

In [ ]:
# Convert our tensor back to numpy array

np.array(T), type(np.array(T))

In [ ]:
# Convert tensor T to a Numpy array

T.numpy(), type(T.numpy())

In [ ]:
T = tf.constant([3.])
T.numpy()[0]

In [ ]:
# The default types of each are slightly differnt

numpy_T = tf.constant(np.array([3.,7.,10.]))
tensor_T = tf.constant([3.,7.,10.])

# Check the datatypes of each

numpy_T.dtype, tensor_T.dtype

# One of the main differences between a TensorFlow tensor and a Numpy    
# is that TensorFlow tensor can be used GPU

## Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()


** If you have access to CUDA-enabled GPU Tensorflow will automatically using it

In [ ]:
!nvidia-smi

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())